# Generated by Django 3.2.6 on 2021-08-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210829_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
